# fly.toml app configuration file generated for crmclient on 2023-07-14T08:30:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crmclient"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
